### PR TITLE
08_ruby/001_グループ分け問題.md. コードレビュー依頼

### PR DESCRIPTION
**Pull request by satohirok**
## 課題のリンク

https://github.com/happiness-chain/practice/blob/main/08_ruby/001_%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%97%E5%88%86%E3%81%91%E5%95%8F%E9%A1%8C.md

## やったこと

上記課題の実施→完了致しました。

## 動作確認方法

hc_practice > rubyディレクトリにて
``ruby random.rb``コマンドを叩く

## その他

実行結果
satouhiroki@satouhiokinoAir ruby % ruby random.rb
"3人と3人にランダムに分ける"
["C", "D", "F"]
["A", "B", "E"]
"2人と4人にランダムに分ける"
["C", "D"]
["A", "B", "E", "F"]
satouhiroki@satouhiokinoAir ruby % ruby random.rb
"3人と3人にランダムに分ける"
["A", "D", "E"]
["B", "C", "F"]
"2人と4人にランダムに分ける"
["A", "D"]
["B", "C", "E", "F"]
satouhiroki@satouhiokinoAir ruby % ruby random.rb
"3人と3人にランダムに分ける"
["A", "C", "D"]
["B", "E", "F"]
"2人と4人にランダムに分ける"
["A", "C"]
["B", "D", "E", "F"]
satouhiroki@satouhiokinoAir ruby % ruby random.rb
"3人と3人にランダムに分ける"
["C", "D", "E"]
["A", "B", "F"]
"2人と4人にランダムに分ける"
["C", "E"]
["A", "B", "D", "F"]
satouhiroki@satouhiokinoAir ruby % ruby random.rb
"3人と3人にランダムに分ける"
["B", "C", "E"]
["A", "D", "F"]
"2人と4人にランダムに分ける"
["C", "E"]
["A", "B", "D", "F"]

### CODE REVIEW

**Review by yamaryo416 — COMMENTED** [review]
こちら、一回実行した際に、
片方のみ実行されるようにしてみましょう！

**Comment by satohirok** [comment]
> こちら、一回実行した際に、
> 片方のみ実行されるようにしてみましょう！

上記修正致しました！

実行結果↓
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "D"]
["B", "C", "E", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "C", "D", "F"]
["A", "E"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "F"]
["B", "C", "D", "E"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "B", "C"]
["D", "E", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "D", "E", "F"]
["B", "C"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "B", "D", "F"]
["C", "E"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["D", "E"]
["A", "B", "C", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "C", "D", "E"]
["A", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "C", "D", "E"]
["A", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "D", "F"]
["A", "C", "E"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "C"]
["A", "D", "E", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "D"]
["B", "C", "E", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["C", "D", "E", "F"]
["A", "B"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["D", "E"]
["A", "B", "C", "F"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["A", "D", "E", "F"]
["B", "C"]
satouhiroki@satouhirokinoMacBook-Air ruby % ruby random.rb
["B", "E", "F"]
["A", "C", "D"]

**Comment by satohirok** [comment]
↑すみません。こちらコメントアウトを消し忘れていたので修正致しました。
改めてご確認宜しくお願い致します。

**Review by yamaryo416 — APPROVED** [review]
LGTMです！

**Pull request merged**
